/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as IndexImport } from './routes/index'
import { Route as CompetitionsIndexImport } from './routes/competitions/index'
import { Route as CompetitionsNewImport } from './routes/competitions/new'
import { Route as CompetitionsIdImport } from './routes/competitions/$id'

// Create/Update Routes

const IndexRoute = IndexImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const CompetitionsIndexRoute = CompetitionsIndexImport.update({
  path: '/competitions/',
  getParentRoute: () => rootRoute,
} as any)

const CompetitionsNewRoute = CompetitionsNewImport.update({
  path: '/competitions/new',
  getParentRoute: () => rootRoute,
} as any)

const CompetitionsIdRoute = CompetitionsIdImport.update({
  path: '/competitions/$id',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/competitions/$id': {
      id: '/competitions/$id'
      path: '/competitions/$id'
      fullPath: '/competitions/$id'
      preLoaderRoute: typeof CompetitionsIdImport
      parentRoute: typeof rootRoute
    }
    '/competitions/new': {
      id: '/competitions/new'
      path: '/competitions/new'
      fullPath: '/competitions/new'
      preLoaderRoute: typeof CompetitionsNewImport
      parentRoute: typeof rootRoute
    }
    '/competitions/': {
      id: '/competitions/'
      path: '/competitions'
      fullPath: '/competitions'
      preLoaderRoute: typeof CompetitionsIndexImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren({
  IndexRoute,
  CompetitionsIdRoute,
  CompetitionsNewRoute,
  CompetitionsIndexRoute,
})

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.jsx",
      "children": [
        "/",
        "/competitions/$id",
        "/competitions/new",
        "/competitions/"
      ]
    },
    "/": {
      "filePath": "index.jsx"
    },
    "/competitions/$id": {
      "filePath": "competitions/$id.jsx"
    },
    "/competitions/new": {
      "filePath": "competitions/new.jsx"
    },
    "/competitions/": {
      "filePath": "competitions/index.jsx"
    }
  }
}
ROUTE_MANIFEST_END */
